package com.m.im.common.entity;

import com.m.im.common.util.core.Table;
import com.m.im.common.entity.model.BaseMUser;

/**
 * Generated by JPress.
 */
@Table(tableName="user",primaryKey="id")
public class MUser extends BaseMUser<MUser> {
	
}
